### ISSUE TITLE
docker-compose up: cql submit application error

### ISSUE THREAD

**Issue by leopeng1995** [HuaweiBigData/StreamCQL#58]
Like #50 ，cql works well in the official setup environment:

```
bin/zkServer.sh start
nohup storm nimbus &
nohup storm supervisor &
nohup storm ui &
```

However, it fails in Docker-Compose. After I execute `docker-compose up`, the Storm 1.0.2 started. I retry the same command in cql. I got a error: `ERROR CQL-99000: An error occurred in CQL Engine.`

I found its explaination in docs: `CQL-99000: Common server exception`. I thought this is a network problem?

It's my docker-compose.yml:
```
version: '2'
services:
    zookeeper:
        image: zookeeper:3.4
        container_name: zookeeper
        restart: always

    nimbus:
        image: storm:1.0.2
        container_name: nimbus
        command: storm nimbus
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 6627:6627

    supervisor:
        image: storm:1.0.2
        container_name: supervisor
        command: storm supervisor
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
        restart: always

    ui:
        image: storm:1.0.2
        container_name: ui
        command: storm ui
        depends_on:
            - nimbus
            - supervisor
            - zookeeper
        links:
            - nimbus
            - supervisor
            - zookeeper
        restart: always
        ports:
            - 8080:8080
```
